/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator.gui;

/**
 *
 * @author kakam
 */
public class JframeGui extends javax.swing.JFrame {

    /**
     * Creates new form JframeGui
     */
    public JframeGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btPercent = new javax.swing.JButton();
        btCE = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();
        btSeven = new javax.swing.JButton();
        btEight = new javax.swing.JButton();
        btNine = new javax.swing.JButton();
        btMult = new javax.swing.JButton();
        btFour = new javax.swing.JButton();
        btFive = new javax.swing.JButton();
        btSix = new javax.swing.JButton();
        btSub = new javax.swing.JButton();
        btOne = new javax.swing.JButton();
        btTwo = new javax.swing.JButton();
        btThree = new javax.swing.JButton();
        btAd = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        brZero = new javax.swing.JButton();
        btVirg = new javax.swing.JButton();
        btEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator's Cauadsm");

        tfValor.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0,00");
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        btPercent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btPercent.setText("%");
        jPanel1.add(btPercent);

        btCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCE.setText("CE");
        btCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCEActionPerformed(evt);
            }
        });
        jPanel1.add(btCE);

        btAC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAC.setText("AC");
        jPanel1.add(btAC);

        btDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDiv.setText("/");
        jPanel1.add(btDiv);

        btSeven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSeven.setText("7");
        btSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSevenActionPerformed(evt);
            }
        });
        jPanel1.add(btSeven);

        btEight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btEight.setText("8");
        btEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEightActionPerformed(evt);
            }
        });
        jPanel1.add(btEight);

        btNine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNine.setText("9");
        btNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNineActionPerformed(evt);
            }
        });
        jPanel1.add(btNine);

        btMult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMult.setText("*");
        btMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultActionPerformed(evt);
            }
        });
        jPanel1.add(btMult);

        btFour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btFour.setText("4");
        btFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFourActionPerformed(evt);
            }
        });
        jPanel1.add(btFour);

        btFive.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btFive.setText("5");
        btFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiveActionPerformed(evt);
            }
        });
        jPanel1.add(btFive);

        btSix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSix.setText("6");
        btSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSixActionPerformed(evt);
            }
        });
        jPanel1.add(btSix);

        btSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSub.setText("-");
        btSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubActionPerformed(evt);
            }
        });
        jPanel1.add(btSub);

        btOne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btOne.setText("1");
        btOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOneActionPerformed(evt);
            }
        });
        jPanel1.add(btOne);

        btTwo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTwo.setText("2");
        btTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTwoActionPerformed(evt);
            }
        });
        jPanel1.add(btTwo);

        btThree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThree.setText("3");
        btThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThreeActionPerformed(evt);
            }
        });
        jPanel1.add(btThree);

        btAd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAd.setText("+");
        jPanel1.add(btAd);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jButton17);

        brZero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brZero.setText("0");
        brZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brZeroActionPerformed(evt);
            }
        });
        jPanel1.add(brZero);

        btVirg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVirg.setText(",");
        jPanel1.add(btVirg);

        btEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btEqual.setText("=");
        jPanel1.add(btEqual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(tfValor))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void btCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCEActionPerformed

    private void btSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSevenActionPerformed
        digitOn("7");
    }//GEN-LAST:event_btSevenActionPerformed

    private void btSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubActionPerformed

    private void btMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMultActionPerformed

    private void btEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEightActionPerformed
        digitOn("8");
    }//GEN-LAST:event_btEightActionPerformed

    private void btNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNineActionPerformed
        digitOn("9");
    }//GEN-LAST:event_btNineActionPerformed

    private void btFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFourActionPerformed
        digitOn("4");
    }//GEN-LAST:event_btFourActionPerformed

    private void btFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiveActionPerformed
        digitOn("5");
    }//GEN-LAST:event_btFiveActionPerformed

    private void btSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSixActionPerformed
        digitOn("6");
    }//GEN-LAST:event_btSixActionPerformed

    private void btOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOneActionPerformed
        digitOn("1");
    }//GEN-LAST:event_btOneActionPerformed

    private void btTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTwoActionPerformed
        digitOn("2");
    }//GEN-LAST:event_btTwoActionPerformed

    private void btThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThreeActionPerformed
        digitOn("3");
    }//GEN-LAST:event_btThreeActionPerformed

    private void brZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brZeroActionPerformed
        digitOn("0");
    }//GEN-LAST:event_brZeroActionPerformed

    private void digitOn(String charr) {
        if (tfValor.getText().equals("0,00")) {
            tfValor.setText(charr);
        } else {
            if (charr.equals(",") && tfValor.getText().contains(",")){
            }else
            {    
                tfValor.setText(tfValor.getText().concat(charr));
            }   
            
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brZero;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btAd;
    private javax.swing.JButton btCE;
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btEight;
    private javax.swing.JButton btEqual;
    private javax.swing.JButton btFive;
    private javax.swing.JButton btFour;
    private javax.swing.JButton btMult;
    private javax.swing.JButton btNine;
    private javax.swing.JButton btOne;
    private javax.swing.JButton btPercent;
    private javax.swing.JButton btSeven;
    private javax.swing.JButton btSix;
    private javax.swing.JButton btSub;
    private javax.swing.JButton btThree;
    private javax.swing.JButton btTwo;
    private javax.swing.JButton btVirg;
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
